### Get cardByNumber
GET http://localhost:8080/api/card/1

### Get Nbp
GET http://localhost:8080/api/nbp/USD/200

###Utworzenie
GET http://localhost:8080/api/currency/22237788822/USD

###
PUT http://localhost:8080/api/card/22344334
Content-Type: application/json

{
  "personName": "weeww2",
  "numberAccount": "22237788822",
  "name": "karta Mastercard Lojalnosciow1111a",
  "numberCard": "22344334"
}
###
GET http://localhost:8080/api/persons/konto bankowe Karoliny Mrówkiaccountdeposits
###
PUT http://localhost:8080/api/persons/acc
Content-Type: application/json

{
  "name": "acc",
  "lastName": "Mrowkaaa",
  "email": "karolina.mrottwka@interia.pl"
}

###Utworzenie osoby
POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "name": "acc",
  "email": "karolina.mrowka@interia.pl",
  "birthday": "2000-05-05",
  "firstName": "Karolina",
  "lastName": "Arowka",
  "pesel":"78062761919",
  "address": {
    "street": "Czachowskiego",
    "number": 2,
    "numberFlat": 4,
    "postCode": "23-900",
    "city": "krakow"

  }

}
###
POST http://localhost:8080/api/account
Content-Type: application/json

{ "name": "konto bankowe Karoliny Mrówki",
  "numberAccount": "22237788822",
  "balance": 333.22,

  "nameAccount": "nameAccount"

}
###
PUT http://localhost:8080/api/account/22237788822
Content-Type: application/json

{
  "numberAccount": "22237788822",
  "balance": 333.20,

  "nameAccount": "nameAccountupdate"

}
###
PUT http://localhost:8080/api/card/2233343344401
Content-Type: application/json

{

"numberAccount": "22237788822",
  "numberCard": "2233343344401",

  "name": "karta Mastercard Loja4sciowa"
}
###

PUT http://localhost:8080/api/kafka/update
Content-Type: application/json

{
  "id": 1,

"street": "Krakowuuu",
    "postCode": "232-900",
    "city": "krakowu"
}


###
GET http://localhost:8080/api/card/account/22237788822
###
DELETE http://localhost:8080/api/persons/1
